import "@/app/globals.css";
import { ChatBar } from "@/features/chat/chat-bar";
import NavBar from './navbar';
import SideBar from './sidebar';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      {/* <AuthGuard> */}
      <div className="flex h-dvh w-screen flex-row">
        <div className="w-1/6 border-r-1 border-r-slate-300">
          <SideBar />
        </div>
        <div className="flex w-5/6 flex-col">
          <div className="flex-shrink-0 border-b-1 border-b-slate-300">
            <NavBar />
          </div>
          <div className="flex flex-1 flex-row overflow-hidden">
            <main className="text-primary flex-1 overflow-y-auto">{children}</main>
            <div className="flex flex-shrink-0 border-l-1 border-l-slate-300">
              <ChatBar />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
