INSERT INTO "public"."dictionaries" 
("id", "code", "name", "metadata", "description") 
VALUES 
('1', 'areas', '{"en":"Area","ru":"Район","th":"พื้นที่"}', '{"info": "Administrative or commonly known zones in which the property is located. Useful for geographical search filters and grouping listings by region"}', '{"en": "Select the property’s geographical area", "ru": "Выберите район недвижимости", "th": "เลือกพื้นที่ของอสังหาริมทรัพย์"}'),
('2', 'location_strengths', '{"en":"Location Strength","ru":"Преимущество Местоположения","th":"ทำเล/จุดแข็ง"}', '{"info": "Macro-level desirability of a location based on geography, infrastructure, or prestige. Often influences price and investment value"}', '{"en": "Choose location desirability factors", "ru": "Выберите преимущества местоположения", "th": "เลือกจุดเด่นของทำเล"}'),
('3', 'highlights', '{"en":"Highlights","ru":"Особенности","th":"จุดเด่น"}', '{"info": "Unique selling points or notable features of the property, such as design, amenities, or views. Used to attract buyer interest and differentiate listings"}', '{"en": "Enter unique property features", "ru": "Укажите уникальные особенности", "th": "ระบุจุดเด่นของอสังหา"}'),
('4', 'transaction_types', '{"en":"Sale or Rent Type","ru":"Тип Продажи или Аренды","th":"ขาย/ให้เช่า"}', '{"info": "Specifies whether the property is for sale, rent, lease, or other transaction types. Crucial for filtering by purpose"}', '{"en": "Select sale or rent type", "ru": "Выберите тип сделки", "th": "เลือกประเภทการขาย/เช่า"}'),
('5', 'property_types', '{"en":"Property Type","ru":"Тип Недвижимости","th":"ประเภทอสังหาริมทรัพย์"}', '{"info": "Categorizes the general type of real estate, such as villa, condo, land, townhouse, or commercial. Helps define the nature of the asset"}', '{"en": "Choose the property type", "ru": "Выберите тип недвижимости", "th": "เลือกประเภทอสังหา"}'),
('6', 'ownership_types', '{"en":"Ownership Type","ru":"Тип Владения","th":"กรรมสิทธิ์"}', '{"info": "Legal form of ownership or title, such as freehold, leasehold, or company-owned. Important for compliance and legal clarity"}', '{"en": "Specify ownership type", "ru": "Укажите тип владения", "th": "ระบุประเภทกรรมสิทธิ์"}'),
('7', 'measurement_units', '{"en":"Measurement Units","ru":"Единицы Измерения","th":"หน่วยวัด"}', '{"info": "Standard units used to express property size (e.g., square meters, square wah, rai). Supports consistent area formatting and comparisons"}', '{"en": "Select property size unit", "ru": "Выберите единицу измерения", "th": "เลือกหน่วยวัดขนาด"}'),
('8', 'divisible_sale_types', '{"en":"Divisible Sale","ru":"Делимая Продажа","th":"แบ่งขาย"}', '{"info": "Indicates whether the property can be subdivided and sold in parts (e.g., per plot, per unit). Useful for land developers or fractional sales"}', '{"en": "Indicate if divisible for sale", "ru": "Укажите, делится ли для продажи", "th": "ระบุว่าแบ่งขายได้หรือไม่"}'),
('9', 'nearby_attractions', '{"en":"Nearby Attractions","ru":"Близлежащие Достопримечательности","th":"สิ่งรอบๆที่น่าสนใจ"}', '{"info": "Landmarks, infrastructure, or lifestyle amenities located near the property (e.g., schools, markets, beaches). Adds location appeal and search relevance"}', '{"en": "List nearby attractions", "ru": "Перечислите близлежащие объекты", "th": "ระบุสถานที่ใกล้เคียง"}'),
('10', 'land_features', '{"en":"Land Features","ru":"Особенности Участка","th":"บนที่ดินมี"}', '{"info": "Describes characteristics or enhancements of the land, such as elevation, slope, access roads, or natural elements. Often relevant in land-only sales or development evaluation"}', '{"en": "Describe land characteristics", "ru": "Опишите особенности участка", "th": "อธิบายลักษณะที่ดิน"}'),
('11', 'land_and_construction', '{"en":"Land and Construction","ru":"Земля и Строительство","th":"ดินและการสร้าง"}', '{"info": "Land and construction features of the property. Useful for filtering and grouping listings by land and construction features"}', '{"en": "Specify land and construction details", "ru": "Укажите детали земли и строительства", "th": "ระบุรายละเอียดที่ดินและการก่อสร้าง"}');