INSERT INTO "public"."dictionaries" 
("id", "code", "name", "metadata", "description") 
VALUES 
('1', 'areas', '{"en":"Area","ru":"Район","th":"พื้นที่"}', '{"info": "Administrative or commonly known zones in which the property is located. Useful for geographical search filters and grouping listings by region"}', '{"en": "Property’s geographical area", "ru": "Район недвижимости", "th": "พื้นที่ของอสังหาริมทรัพย์"}'),
('2', 'location_strengths', '{"en":"Location Strength","ru":"Преимущество Местоположения","th":"จุดเด่นของทำเล"}', '{"info": "Macro-level desirability of a location based on geography, infrastructure, or prestige. Often influences price and investment value"}', '{"en": "Location desirability factor", "ru": "Преимущество местоположения", "th": "จุดเด่นของทำเล"}'),
('3', 'highlights', '{"en":"Highlight","ru":"Особенность","th":"จุดเด่น"}', '{"info": "Unique selling points or notable features of the property, such as design, amenities, or views. Used to attract buyer interest and differentiate listings"}', '{"en": "Unique property feature", "ru": "Уникальная особенность", "th": "จุดเด่นของอสังหาริมทรัพย์"}'),
('5', 'property_types', '{"en":"Property Type","ru":"Тип Недвижимости","th":"ประเภทอสังหาริมทรัพย์"}', '{"info": "Categorizes the general type of real estate, such as villa, condo, land, townhouse, or commercial. Helps define the nature of the asset"}', '{"en": "Property type", "ru": "Тип недвижимости", "th": "ประเภทอสังหาริมทรัพย์"}'),
('6', 'ownership_types', '{"en":"Ownership Type","ru":"Тип Владения","th":"ประเภทกรรมสิทธิ์"}', '{"info": "Legal form of ownership or title, such as freehold, leasehold, or company-owned. Important for compliance and legal clarity"}', '{"en": "Ownership type", "ru": "Тип владения", "th": "ประเภทกรรมสิทธิ์"}'),
('7', 'measurement_units', '{"en":"Measurement Unit","ru":"Единица Измерения","th":"หน่วยวัด"}', '{"info": "Standard units used to express property size (e.g., square meters, square wah, rai). Supports consistent area formatting and comparisons"}', '{"en": "Property size unit", "ru": "Единица измерения площади", "th": "หน่วยวัดขนาด"}'),
('8', 'divisible_sale_types', '{"en":"Divisible Sale","ru":"Делимая Продажа","th":"การแบ่งขาย"}', '{"info": "Indicates whether the property can be subdivided and sold in parts (e.g., per plot, per unit). Useful for land developers or fractional sales"}', '{"en": "Divisible sale", "ru": "Делимая продажа", "th": "การแบ่งขาย"}'),
('9', 'nearby_attractions', '{"en":"Nearby Attraction","ru":"Близлежащая Достопримечательность","th":"สถานที่ท่องเที่ยวใกล้เคียง"}', '{"info": "Landmarks, infrastructure, or lifestyle amenities located near the property (e.g., schools, markets, beaches). Adds location appeal and search relevance"}', '{"en": "Nearby attraction", "ru": "Близлежащий объект", "th": "สถานที่ท่องเที่ยวใกล้เคียง"}'),
('10', 'land_features', '{"en":"Land Feature","ru":"Особенность Участка","th":"ลักษณะของที่ดิน"}', '{"info": "Describes characteristics or enhancements of the land, such as elevation, slope, access roads, or natural elements. Often relevant in land-only sales or development evaluation"}', '{"en": "Land characteristic", "ru": "Особенность участка", "th": "ลักษณะที่ดิน"}'),
('11', 'land_and_construction', '{"en":"Land and Construction","ru":"Земля и Строительство","th":"ที่ดินและการก่อสร้าง"}', '{"info": "Land and construction features of the property. Useful for filtering and grouping listings by land and construction features"}', '{"en": "Land and construction detail", "ru": "Деталь земли и строительства", "th": "รายละเอียดที่ดินและการก่อสร้าง"}');